image: python:3.12

stages:
  - build
  - test
  - package

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - mkdir -p static/dataset
  - echo "src_id,dst_id,count,mindate,maxdate" > static/dataset/bitcoin.links.csv
  - echo "a,b,1,20200101T000000,20200101T000000" >> static/dataset/bitcoin.links.csv
  - echo "b,c,2,20200102T000000,20200102T000000" >> static/dataset/bitcoin.links.csv

build-job:
  stage: build
  script:
    - echo "Building the project..."
    - ls
    - echo "Build completed successfully."

test:
  stage: test
  script:
    - python -m unittest discover

package-job:
  image: docker:24.0.5  # Versão mais previsível e segura
  services:
    - docker:24.0.5-dind
  stage: package
  before_script: []  # Sobrescreve o before_script para este job
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE 
  rules:  # Substitui `only`, mais flexível
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always  # Garante que o job sempre será executado na branch main

